version: '3'

services:
  prd:
    container_name: stack-readme-prd
    build:
      context: .
      dockerfile: stack-readme-prd.dockerfile
      args:
        - api_key=${STACK_EXCHANGE_API_KEY}
    ports:
      - '3070:3070'
  dev:
    container_name: stack-readme-dev
    build:
      context: .
      dockerfile: stack-readme-dev.dockerfile
      args:
        - api_key=${STACK_EXCHANGE_API_KEY}
    ports:
      - '3071:3071'
