version: '2'

services:
  se-readme-dev:
    container_name: stack-readme-dev
    build:
      context: .
      dockerfile: stack-readme-dev.dockerfile
      args:
        - api_key=${STACK_EXCHANGE_API_KEY}
    ports:
      - '3040:3040'
  se-readme-prd:
    container_name: stack-readme-prd
    build:
      context: .
      dockerfile: stack-readme-prd.dockerfile
      args:
        - api_key=${STACK_EXCHANGE_API_KEY}
    ports:
      - '3344:3344'
